// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.1
// 	protoc        v3.21.12
// source: pkg/proto/vocation.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Vocation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VocID         uint64                 `protobuf:"varint,4,opt,name=VocID,proto3" json:"VocID,omitempty"`
	UserID        uint64                 `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	Email         string                 `protobuf:"bytes,5,opt,name=Email,proto3" json:"Email,omitempty"`
	StartTime     string                 `protobuf:"bytes,2,opt,name=StartTime,proto3" json:"StartTime,omitempty"`
	EndTime       string                 `protobuf:"bytes,3,opt,name=EndTime,proto3" json:"EndTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vocation) Reset() {
	*x = Vocation{}
	mi := &file_pkg_proto_vocation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vocation) ProtoMessage() {}

func (x *Vocation) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_vocation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vocation.ProtoReflect.Descriptor instead.
func (*Vocation) Descriptor() ([]byte, []int) {
	return file_pkg_proto_vocation_proto_rawDescGZIP(), []int{0}
}

func (x *Vocation) GetVocID() uint64 {
	if x != nil {
		return x.VocID
	}
	return 0
}

func (x *Vocation) GetUserID() uint64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *Vocation) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Vocation) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *Vocation) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

type DeleteVocationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        uint64                 `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteVocationRequest) Reset() {
	*x = DeleteVocationRequest{}
	mi := &file_pkg_proto_vocation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteVocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVocationRequest) ProtoMessage() {}

func (x *DeleteVocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_vocation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVocationRequest.ProtoReflect.Descriptor instead.
func (*DeleteVocationRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_vocation_proto_rawDescGZIP(), []int{1}
}

func (x *DeleteVocationRequest) GetUserID() uint64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

type AddVocationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vocation      *Vocation              `protobuf:"bytes,1,opt,name=vocation,proto3" json:"vocation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddVocationRequest) Reset() {
	*x = AddVocationRequest{}
	mi := &file_pkg_proto_vocation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddVocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddVocationRequest) ProtoMessage() {}

func (x *AddVocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_vocation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddVocationRequest.ProtoReflect.Descriptor instead.
func (*AddVocationRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_vocation_proto_rawDescGZIP(), []int{2}
}

func (x *AddVocationRequest) GetVocation() *Vocation {
	if x != nil {
		return x.Vocation
	}
	return nil
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=Error,proto3" json:"Error,omitempty"`
	Status        int64                  `protobuf:"varint,2,opt,name=Status,proto3" json:"Status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_pkg_proto_vocation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_vocation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_pkg_proto_vocation_proto_rawDescGZIP(), []int{3}
}

func (x *Response) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *Response) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

type GetVocationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        uint64                 `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVocationRequest) Reset() {
	*x = GetVocationRequest{}
	mi := &file_pkg_proto_vocation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVocationRequest) ProtoMessage() {}

func (x *GetVocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_vocation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVocationRequest.ProtoReflect.Descriptor instead.
func (*GetVocationRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_vocation_proto_rawDescGZIP(), []int{4}
}

func (x *GetVocationRequest) GetUserID() uint64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

type GetVocationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      *Response              `protobuf:"bytes,2,opt,name=response,proto3" json:"response,omitempty"`
	Vocation      *Vocation              `protobuf:"bytes,1,opt,name=vocation,proto3" json:"vocation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVocationResponse) Reset() {
	*x = GetVocationResponse{}
	mi := &file_pkg_proto_vocation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVocationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVocationResponse) ProtoMessage() {}

func (x *GetVocationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_vocation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVocationResponse.ProtoReflect.Descriptor instead.
func (*GetVocationResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_vocation_proto_rawDescGZIP(), []int{5}
}

func (x *GetVocationResponse) GetResponse() *Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *GetVocationResponse) GetVocation() *Vocation {
	if x != nil {
		return x.Vocation
	}
	return nil
}

var File_pkg_proto_vocation_proto protoreflect.FileDescriptor

var file_pkg_proto_vocation_proto_rawDesc = []byte{
	0x0a, 0x18, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x76, 0x6f, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x76, 0x6f, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x22, 0x86, 0x01, 0x0a, 0x08, 0x56, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x14, 0x0a, 0x05, 0x56, 0x6f, 0x63, 0x49, 0x44, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x05, 0x56, 0x6f, 0x63, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49,
	0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12,
	0x14, 0x0a, 0x05, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x45, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x1c, 0x0a, 0x09, 0x53, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x53, 0x74, 0x61, 0x72, 0x74, 0x54,
	0x69, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x45, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x45, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x2f, 0x0a,
	0x15, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x56, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x22, 0x44,
	0x0a, 0x12, 0x41, 0x64, 0x64, 0x56, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x2e, 0x0a, 0x08, 0x76, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x76, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x2e, 0x56, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x08, 0x76, 0x6f, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x22, 0x38, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x2c,
	0x0a, 0x12, 0x47, 0x65, 0x74, 0x56, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x22, 0x75, 0x0a, 0x13,
	0x47, 0x65, 0x74, 0x56, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x2e, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x76, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x2e, 0x0a, 0x08, 0x76, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x76, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x2e, 0x56, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x08, 0x76, 0x6f, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x32, 0xcd, 0x01, 0x0a, 0x0f, 0x56, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x37, 0x0a, 0x03, 0x41, 0x64, 0x64, 0x12, 0x1c,
	0x2e, 0x76, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x41, 0x64, 0x64, 0x56, 0x6f, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x76,
	0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x3d, 0x0a, 0x06, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x1f, 0x2e, 0x76, 0x6f, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x56, 0x6f, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x76, 0x6f,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x42, 0x0a, 0x03, 0x47, 0x65, 0x74, 0x12, 0x1c, 0x2e, 0x76, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x2e, 0x47, 0x65, 0x74, 0x56, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x76, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e,
	0x47, 0x65, 0x74, 0x56, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x42, 0x10, 0x5a, 0x0e, 0x2e, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_proto_vocation_proto_rawDescOnce sync.Once
	file_pkg_proto_vocation_proto_rawDescData = file_pkg_proto_vocation_proto_rawDesc
)

func file_pkg_proto_vocation_proto_rawDescGZIP() []byte {
	file_pkg_proto_vocation_proto_rawDescOnce.Do(func() {
		file_pkg_proto_vocation_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_proto_vocation_proto_rawDescData)
	})
	return file_pkg_proto_vocation_proto_rawDescData
}

var file_pkg_proto_vocation_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_pkg_proto_vocation_proto_goTypes = []any{
	(*Vocation)(nil),              // 0: vocation.Vocation
	(*DeleteVocationRequest)(nil), // 1: vocation.DeleteVocationRequest
	(*AddVocationRequest)(nil),    // 2: vocation.AddVocationRequest
	(*Response)(nil),              // 3: vocation.Response
	(*GetVocationRequest)(nil),    // 4: vocation.GetVocationRequest
	(*GetVocationResponse)(nil),   // 5: vocation.GetVocationResponse
}
var file_pkg_proto_vocation_proto_depIdxs = []int32{
	0, // 0: vocation.AddVocationRequest.vocation:type_name -> vocation.Vocation
	3, // 1: vocation.GetVocationResponse.response:type_name -> vocation.Response
	0, // 2: vocation.GetVocationResponse.vocation:type_name -> vocation.Vocation
	2, // 3: vocation.VocationService.Add:input_type -> vocation.AddVocationRequest
	1, // 4: vocation.VocationService.Delete:input_type -> vocation.DeleteVocationRequest
	4, // 5: vocation.VocationService.Get:input_type -> vocation.GetVocationRequest
	3, // 6: vocation.VocationService.Add:output_type -> vocation.Response
	3, // 7: vocation.VocationService.Delete:output_type -> vocation.Response
	5, // 8: vocation.VocationService.Get:output_type -> vocation.GetVocationResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pkg_proto_vocation_proto_init() }
func file_pkg_proto_vocation_proto_init() {
	if File_pkg_proto_vocation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_proto_vocation_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_vocation_proto_goTypes,
		DependencyIndexes: file_pkg_proto_vocation_proto_depIdxs,
		MessageInfos:      file_pkg_proto_vocation_proto_msgTypes,
	}.Build()
	File_pkg_proto_vocation_proto = out.File
	file_pkg_proto_vocation_proto_rawDesc = nil
	file_pkg_proto_vocation_proto_goTypes = nil
	file_pkg_proto_vocation_proto_depIdxs = nil
}
